name: resmedia_taporty_core
description: Common shared code for Taporty mobile apps

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  intl: ^0.16.0
  path: ^1.6.4
  google_sign_in: ^4.1.1
  geolocator: ^5.1.5
  cloud_functions: ^0.4.1+6
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.3+1
  firebase_messaging: ^6.0.9
  dash: ^0.5.5
  rxdart: ^0.23.1
  google_maps_flutter: ^0.5.21+15
  shared_preferences: ^0.5.6+1

  flutter_localizations:
    sdk: flutter

  # Scritti e implementati da Simone o Giorgio.
  easy_blocs:
    path: ../plugins/easy_blocs
  easy_stripe:
    path: ../plugins/easy_stripe
  easy_firebase:
    path: ../plugins/easy_firebase

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Sistemati e controllati da Emilio.
  # QUesto comando è sia per json che per dash per tutti quelli che dipendono da questo plugin
  build_runner: ^1.7.3 # flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^3.2.5
  dash_generator: ^0.5.5
  flutter_launcher_icons: ^0.7.4