name: resmedia_taporty_core
description: Common shared code for Taporty mobile apps

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.0
  intl: ^0.16.0
  path: ^1.6.4
  google_sign_in: ^4.1.1
  geolocator: ^5.1.5
  cloud_functions: 0.4.1+8
  cloud_firestore: ^0.13.4
  geoflutterfire: ^2.1.0
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.4
  firebase_messaging: ^6.0.9
  dash: ^0.5.7
  rxdart: ^0.23.1
  google_maps_flutter: ^0.5.21+15
  shared_preferences: ^0.5.6+1
  stripe_payment: ^1.0.6
  overlay_support: ^1.0.2


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Sistemati e controllati da Emilio.
  # QUesto comando è sia per json che per dash per tutti quelli che dipendono da questo plugin
  build_runner: ^1.7.3 # flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^3.2.5
  dash_generator: ^0.5.5
  flutter_launcher_icons: ^0.7.4