name: resmedia_taporty_core
description: Common shared code for Taporty mobile apps

version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.0
  google_sign_in: ^4.1.1
  url_launcher: ^5.4.1
  flutter_calendar_carousel: ^1.4.10
  flutter_svg: ^0.15.0
  json_annotation: ^3.0.0
  flutter_google_places: ^0.2.3
  path_provider: ^1.5.1
  image_picker: ^0.6.2
  intl: ^0.16.0
  shared_preferences: ^0.5.6
  geolocator: ^5.1.5
  geocoder: ^0.2.1
  toast: ^0.1.5
  auto_size_text: ^2.1.0
  google_maps_flutter: ^0.5.21
  location: ^2.3.5
  permission_handler: ^4.0.0
  cached_network_image: ^2.0.0-rc
  vibration: ^1.2.2
  file_picker: ^1.4.3
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.5.0
  flutter_sticky_header: ^0.4.0
  google_maps_webservice: ^0.0.16
  flutter_slidable: ^0.5.4
  cloud_functions: ^0.4.1
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.0
  firebase_auth: ^0.15.2
  firebase_messaging: ^6.0.8
  mailer: ^3.0.4
  rubber: ^0.4.0
  flutter_local_notifications: ^0.8.4
  dash: ^0.5.5
  rxdart: ^0.22.6
  sticky_headers: ^0.1.8+1
  rating_bar: ^0.2.0

  flutter_localizations:
    sdk: flutter

  # Scritti e implementati da Simone o Giorgio.
  easy_blocs:
    path: ../plugins/easy_blocs
  easy_stripe:
    path: ../plugins/easy_stripe
  easy_firebase:
    path: ../plugins/easy_firebase

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Sistemati e controllati da Emilio.
  # QUesto comando è sia per json che per dash per tutti quelli che dipendono da questo plugin
  build_runner: ^1.7.2 # flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^3.2.3
  dash_generator: ^0.5.5
  flutter_launcher_icons: ^0.7.4