name: resmedia_taporty_customer
description: Mobile app for Taporty

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Sistemati e controllati da Emilio.
  google_sign_in: ^4.1.1
  url_launcher: ^5.4.1
  json_annotation: ^3.0.0
  flutter_google_places: 
    git: git://github.com/FedeZara/flutter_google_places.git
  image_picker: ^0.6.2
  intl: ^0.16.0
  shared_preferences: ^0.5.6
  geolocator: ^5.1.5
  toast: ^0.1.5
  auto_size_text: ^2.1.0
  google_maps_flutter: ^0.5.21
  location: ^2.3.5
  cached_network_image: ^2.0.0
  vibration: ^1.2.2
  font_awesome_flutter: ^8.5.0
  flutter_sticky_header: ^0.4.0
  google_maps_webservice: ^0.0.16
  flutter_slidable: ^0.5.4
  cloud_functions: ^0.4.1
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.0
  firebase_auth: ^0.15.2
  firebase_messaging: ^6.0.8
  flutter_local_notifications: ^0.8.4
  dash: ^0.5.5
  rxdart: ^0.23.1
  sticky_headers: ^0.1.8+1
  rating_bar: ^0.2.0
  tuple: ^1.0.3

  flutter_localizations:
    sdk: flutter

  resmedia_taporty_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Sistemati e controllati da Emilio.
  # QUesto comando è sia per json che per dash per tutti quelli che dipendono da questo plugin
  build_runner: ^1.7.2 # flutter packages pub run build_runner build --delete-conflicting-outputs
  json_serializable: ^3.2.3
  dash_generator: ^0.5.5
  flutter_launcher_icons: ^0.7.4


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/img/
    - assets/img/home/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path: "assets/ic_launcher.png"
  image_path_ios: "assets/ic_launcher-ios.jpg"
  #  image_path_ios: "assets/images/icon-710x599-ios.png"
  ios: true
  android: true # can specify file name here e.g. "ic_launcher"
