enum OrderStates {
  NEW = "NEW",
  ACCEPTED = "ACCEPTED",
  MODIFIED = "MODIFIED",
  CANCELLED = "CANCELLED",
  READY = "READY",
  PICKED_UP = "PICKED_UP",
  DELIVERED = "DELIVERED",
  ARCHIVED = "ARCHIVED",
  REFUSED = "REFUSED",
}

export default OrderStates;